# Generated by Django 3.2.18 on 2023-04-04 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_backet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backet',
            new_name='Basket',
        ),
    ]
